### ISSUE TITLE
Improve UI Layout

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#100]
# Problem

The current layout leaves a lot of wasted real estate and also means I cannot see the data and the graph at the same time.

# Proposed Solution
 - move the graph under the sequence list
 - have the data pane on the right take the whole side. We can then subdivide the data pane more easily (e.g. to handle large state objects).

![Screen Shot 2024-03-22 at 2 07 23 PM](https://github.com/DAGWorks-Inc/burr/assets/2328071/7e9d51e7-f9d9-4bea-a2e8-53149d06a00b)

**Comment by skrawcz** [comment]
More things:

- [ ] want top bar to stay like you can do in a spreadsheet, so you can toggle raw/render and stay in place.
- [ ] also want how github shows what function you're in when things are collapsed so you know where you are/what you're looking at -- e.g. that could be in the top bar.
- [ ] when the left is minimized, you can't see what the name of the action is that you're on.
- [ ] render forms components should be collapsable -- could even allow people to specify a config as to what to/not to render.

**Comment by elijahbenizzy** [comment]
Most of these are solved by: https://github.com/DAGWorks-Inc/burr/pull/121

**Comment by skrawcz** [comment]
Closing this initial ticket. We can create more.
