### ISSUE TITLE
Simulation example linked from Readme is missing

### ISSUE THREAD

**Issue by HanClinto** [DAGWorks-Inc/burr#134]
The simulation example linked from the Readme sounds interesting, but the folder contains only a single zero byte file. Forgot to upload this code, or else remove the reference?

**Comment by elijahbenizzy** [comment]
@HanClinto thanks for noticing!  Made some changes:

1. Added a placeholder in the repo: https://github.com/DAGWorks-Inc/burr/pull/137
2. Created an issue to track with some ideas -- would love contributions + suggestions! https://github.com/DAGWorks-Inc/burr/issues/136

**Comment by skrawcz** [comment]
@HanClinto I added an example sketch of an application. Does that help? I know it's not a full working example.

**Comment by HanClinto** [comment]
@skrawcz yes it does, thank you! I think I was imagining something like the multi-agent "smallville" example near the end, and I'm glad to see we were on the same page! I certainly want to dig more into Burr and see more of what we all can do with it. I haven't fully wrapped my mind around it yet, but it seems to be addressing a lot of pressing issues in the space of LLM usability and transparency right now.

Thank you very much - I appreciate it!

**Comment by skrawcz** [comment]
> @skrawcz yes it does, thank you! I think I was imagining something like the multi-agent "smallville" example near the end, and I'm glad to see we were on the same page! I certainly want to dig more into Burr and see more of what we all can do with it. I haven't fully wrapped my mind around it yet, but it seems to be addressing a lot of pressing issues in the space of LLM usability and transparency right now.
> 
> Thank you very much - I appreciate it!

Ah okay -- yeah that's a more complex example that blends "simulation" with "agents".  So for something like smallville there could be two levels to think about using Burr:

1. each person could be their own Burr application. 
2. running the whole application could then also be modeled in Burr.

If you find a paper that could be implemented or find some example implementation do send it our way.
