### ISSUE TITLE
Add Simulation Example

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#136]
We have room for an example + have it in the docs. We need to think through what we want to suggest. Some ideas:

1. Time-series forecasting -- do a few steps that forecast each week and move into the future
2. Trading simulation -- similar to (1) -- steps are data preparation, stock forecasting, portfolio construction . We store positions in state and update them -- the update is tricky
3. Something with multiple agents talking to one another?

Please comment if you have preferences (or want to contribute!).

**Comment by zilto** [comment]
Simulation example was added
