### ISSUE TITLE
UI Perf improvement: don't try to render list[float] as individual fields

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#150]
It wont be uncommon to have embeddings in state. 

# Current behavior

Currently we render each dimension as its own field. This slows down the UI when things get large.

## Screenshots
![Screen Shot 2024-04-08 at 3 06 46 PM](https://github.com/DAGWorks-Inc/burr/assets/2328071/17afa218-faec-4318-bda1-19cd6cec72e5)

## Steps to replicate behavior
Use telephone example.
1. save a list of floats
2. see it in state

## Library & System Information
latest.

# Expected behavior
Not each dimension as its own field. A single array view. Or something special for embeddings.
The UI is snappy.

# Additional context
Telephone example saves embeddings.

**Comment by elijahbenizzy** [comment]
This is complete, and we're fixing it with a JSON rendering to look nicer: 
- https://github.com/DAGWorks-Inc/burr/pull/154
- https://github.com/DAGWorks-Inc/burr/pull/151

This said, this is a bit suboptimal. What we should really do is provide types that you can save that are optimized in storage, render, etc... `Embeddings` could have a `Embeddings` view that's respected throughout -- if you save the `Embeddings` data type, we'll show: `dimensions`, `min`, `max`, etc... and can expand out if we want.
