### ISSUE TITLE
Improve persistence + debugging workflow

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#181]
**Is your feature request related to a problem? Please describe.**
There's a problem with the common debugging workflow -- it works but you hit the following:

Resuming from a prior step will end up clobbering the sequence ID, resulting in potentially undefined behavior. 

You can always do this out of band (load up then start a new one), but it should be easy.

**Describe the solution you'd like**

Two possibilities:
1. Load from a sequence ID and "fork" the app (by default)
2. Fast-forward the sequence ID to the latest, regardless

The problem is that `with_identifiers` specifies the sequence ID, which really shouldn't be something the user cares about.

Suggest the following:

```python
.with_identifiers(
    app_id="...", # new app ID
    sequence_id=None # None=0, otherwise it starts at whatever you specify (could be the old one)
) # deprecate sequence_Id from this
.initialize_from(
    persister,
    resume_at_next_action=True,
    default_state=...,
    default_entrypoint=...,
    copy_from="...", # old app ID
    sequence_id=... # old sequence ID
)
```

Then this app stores a "parent" app with a step/fork pointer. This enables you to liknk back/display in the UI.
Note if you put the same App ID in, you'll get the same one, and your sequence ID should just fast forward to where its left off.

Need to think through backwards compatibility here, as this is a little confusing.

**Describe alternatives you've considered**
`.copy_from(...)` for something explicit

**Additional context**
From OS users on discord

**Comment by AshisGhosh** [comment]
LGTM! 
My only suggestion would be to make the `copy_from` and `sequence_id` variables more explicit. E.g. `fork_from_app_id`, `fork_at_sequence_id`

**Comment by skrawcz** [comment]
@AshisGhosh @elijahbenizzy I have:

```python
.initialize_from(
        initializer=tracker,
        resume_at_next_action=False, # we want to always start at human_converse; our entrypoint
        default_entrypoint="human_converse",
        default_state=initial_state, # set some default state incase we can't find the prior state
        fork_from_app_id=prior_app_id, # <---- The new addition 
        fork_from_partition_key="sample_user",  # <---- The new addition 
        fork_from_sequence_id=5,  # <---- The new addition 
    )
```
working

**Comment by elijahbenizzy** [comment]
> @AshisGhosh @elijahbenizzy I have:
> 
> ```python
> .initialize_from(
>         initializer=tracker,
>         resume_at_next_action=False, # we want to always start at human_converse; our entrypoint
>         default_entrypoint="human_converse",
>         default_state=initial_state, # set some default state incase we can't find the prior state
>         fork_from_app_id=prior_app_id, # <---- The new addition 
>         fork_from_partition_key="sample_user",  # <---- The new addition 
>         fork_from_sequence_id=5,  # <---- The new addition 
>     )
> ```
> 
> working here - #184
> 
> Let me know your API feedback/thoughts.

I like it. Feels concistent -- there's:
1. `fork_from_*` -- this is where its loaded _from_
2. `with_identifiers` -- this is where its saved _to_

**Comment by AshisGhosh** [comment]
> > @AshisGhosh @elijahbenizzy I have:
> > ```python
> > .initialize_from(
> >         initializer=tracker,
> >         resume_at_next_action=False, # we want to always start at human_converse; our entrypoint
> >         default_entrypoint="human_converse",
> >         default_state=initial_state, # set some default state incase we can't find the prior state
> >         fork_from_app_id=prior_app_id, # <---- The new addition 
> >         fork_from_partition_key="sample_user",  # <---- The new addition 
> >         fork_from_sequence_id=5,  # <---- The new addition 
> >     )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > working here - #184
> > Let me know your API feedback/thoughts.
> 
> I like it. Feels consistent -- there's:
> 
> 1. `fork_from_*` -- this is where its loaded _from_
> 2. `with_identifiers` -- this is where its saved _to_

Yes, I'm a fan! The flow to revisit a point and branch off is very clear.

**Comment by skrawcz** [comment]
Okay PR is ready I think.

- [ ] Going to leave "Wire through the parent ID" to the UI and persisters as something for later as that's a more involved change. i.e. would be nice to see in the UI what you forked from.
