### ISSUE TITLE
Wire through "parent app ID" when forking an application's state

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#185]
**Is your feature request related to a problem? Please describe.**
We can now fork state. We should track where it came from more explicitly.

**Describe the solution you'd like**
It would be nice to see in the UI what you forked from.
TBD whether the state persisters need to know about this.

**Options / things to consider**

 - Adding a field to state.
 - Adding something like the partition_key, but parent_app_id in addition
 - we have to consider impact on peristers
 - have to consider impact on tracker & UI
 

**Additional context**
Conversations can end up being trees in certain cases if we allow human in the loop, people going back in time, debugging, etc. How do we keep track of it all?

**Comment by elijahbenizzy** [comment]
#189 completes this
