### ISSUE TITLE
Streamed output

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#19]
in the case of an LLM app, people will want to stream a result back.

We need to think through the API a bit.

**Comment by elijahbenizzy** [comment]
Cleaner idea -- why not use generators?

```python
StreamingAction = Generator[
    dict, None, Tuple[dict, State]
]

@action(reads=["query"], writes=["response"])
def streaming_output_action(state: State) -> StreamingAction:
    buffer = []
    for word in ["hello", "world", "this", "is", "a", "test"]:
        buffer.append(word)
        yield {"response": word}
    response = " ".join(buffer)
    return {"response": response}, state.update(response=response)
```

**Comment by elijahbenizzy** [comment]
OK, looking at the API. How do we handle this?

```python
action, state, result = app.step(stream=True)
for item in result['response']:
    yield item # to a streaming response
# or
yield item.get() # field on Stream
```

With `iterate`, it would be the same -- its just that any state field taht's a streaming container would have to resolve before starting the next item...
```
for  action, state, result in app.step(stream=True):
    if action == "streaming_output_action":
        for item in result['response']:
            yield item
        # or
        return result['response'].get()
```

Problems are:
1. How do we handle hooks, traces, trackers, etc... It should end *after* the generator. This means that we may be out of context...
2. How do we ensure that this gets converted to the right shape/item?

**Comment by elijahbenizzy** [comment]
Thinking through:

## Define
```python
@action(reads=["prompt"], writes=["response"])
def action(state: State) -> Generator[dict, None, Tuple[dict, State]]:
    buffer = ""
    for token in query(state["prompt"]):
        buffer += token
        yield token
    return {"response" : buffer}, state.update(response=buffer)
```   

## How to call
```python
result_generator = app.stream_result(halt_after=...)
for result in result_generator: # gives you intermediate result
    yield result['...']
action, state, result = result_generator.get() # blocks till completion

result_generator = app.astream_result(halt_after=...)
async for result in result_generator: # gives you intermediate result
    yield result['...']
action, state, result = result_generator.get() # blocks till completion
```

If its intermediate, we force-resolve it.

**Comment by elijahbenizzy** [comment]
Design decisions from #19:

Implements streaming action

See discussion here: https://github.com/DAGWorks-Inc/burr/issues/19.

Design decisions:
1. We have two APIs -- class-based and functional
2. We leverage the "return value" of a generator -- this will need to be
   explained a bit to the user as it is an odd but useful capability of
   generators
3. We currently only implement synchronous generators. The API for async
   will have to be different (ish) -- we will figure it out later.
4. We allow halt_before and halt_after -- these return
   StreamingResultContainer
5. We only use this to stream the final result in, although we could
   stream intermediate results in if we want.
6. If an intermediate result is streaming, we elect to just run through
   it (by force-exhausting the generator)

**Comment by elijahbenizzy** [comment]
This is complete + released. See #64 for follow-ups.
