### ISSUE TITLE
Style visualization better

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#201]
**Is your feature request related to a problem? Please describe.**
The graphviz viz could be styled better.

**Describe the solution you'd like**
Something that looks nice like https://github.com/dagworks-inc/hamilton 's output.

**Describe alternatives you've considered**
Not doing it

**Additional context**
This should also ensure that we can make visualization more pluggable, e.g. for mermaid.js.

**Comment by zilto** [comment]
Completed in #309
