### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#208]
**Is your feature request related to a problem? Please describe.**
Save to/load from mongoDB.

**Describe the solution you'd like**
MongoDB persister. See the following for an example: https://github.com/DAGWorks-Inc/burr/blob/26cfcd272a26c58e88c6ec84b18682b8ad87a9bd/burr/integrations/persisters/b_redis.py#L19

**Describe alternatives you've considered**

**Additional context**

**Comment by NandaniThakur** [comment]
Hi @elijahbenizzy,

I wanted to let you know that I am new to contributing to open source projects, and this is my first attempt at adding a feature. I have implemented the MongoDB persister as discussed in issue #208. I would appreciate any feedback or guidance you can provide to help me improve my contribution.

Thank you for your understanding and support!

Best regards,
Nandani.

**Comment by skrawcz** [comment]
> Hi @elijahbenizzy,
> 
> I wanted to let you know that I am new to contributing to open source projects, and this is my first attempt at adding a feature. I have implemented the MongoDB persister as discussed in issue #208. I would appreciate any feedback or guidance you can provide to help me improve my contribution.
> 
> Thank you for your understanding and support!
> 
> Best regards, Nandani.

Excellent thanks -- I left comments. This is great, it'll also force us to add tests for the other persisters so thanks for doing this!
