### ISSUE TITLE
Delete `App Runs` button in the project section

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#210]
**Is your feature request related to a problem? Please describe.**
Wasted space, clicking will get you there: 

![image](https://github.com/DAGWorks-Inc/burr/assets/3886307/360a6635-85be-411e-b158-b8b196f6ad3b)

**Describe the solution you'd like**
Deleted.

**Additional context**
Just cleaning up -- coming up with easy issues for first-time contributors.

**Comment by proftorch** [comment]
I'm on it

**Comment by AgnesNM** [comment]
Hello @elijahbenizzy @proftorch @skrawcz was this done, or could I take it up?

**Comment by skrawcz** [comment]
> Hello @elijahbenizzy @proftorch @skrawcz was this done, or could I take it up?

@AgnesNM please - all yours. Since we haven't had an update in a while.

**Comment by elijahbenizzy** [comment]
Hey @AgnesNM -- sorry about this -- turns out I had done this already! If you're looking for some good UI changes to get started, these might be nice:

- https://github.com/DAGWorks-Inc/burr/issues/276
- https://github.com/DAGWorks-Inc/burr/issues/275

My bad! Should have updated this when it's done. If neither of those seem appealing, feel free to comment, I'm sure we can find you something!

**Comment by AgnesNM** [comment]
Thanks @skrawcz loooks like it's already done. @elijahbenizzy let me look at the issues you've suggested.

**Comment by skrawcz** [comment]
@AgnesNM yes apologies on my part - sorry for the confusion!

**Comment by AgnesNM** [comment]
No problem @skrawcz
