### ISSUE TITLE
Disable sequence ID filter default in app list

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#214]
**Is your feature request related to a problem? Please describe.**
We default to hide things that have gotten to zero. We want to show them now.

**Describe the solution you'd like**
Change the default to be unchecked: 
![image](https://github.com/DAGWorks-Inc/burr/assets/3886307/9665c081-0076-4aa3-85d9-fcaa4b991e22)

**Additional context**
Was doing this for streamlit cause it created a ton of junk, but easier not to have it.

**Comment by zilto** [comment]
This feature was successfully added
