### ISSUE TITLE
Structured Output Examples

### ISSUE THREAD

**Issue by HamzaFarhan** [DAGWorks-Inc/burr#240]
**Is your feature request related to a problem? Please describe.**
I just found out about Burr and it looks super promising. I primarily use [Instructor](https://python.useinstructor.com/) for my projects to get structured outputs from LLMs and I wanted to see if it worked with Burr. And it does!!

**Describe the solution you'd like**
I would be happy to add some examples using both Burr and Instructor.

**Describe alternatives you've considered**
I love the freedom it has when compared to other tools/frameworks.

**Additional context**
I have noticed that this is a TODO like [here](https://github.com/DAGWorks-Inc/burr/blob/d5dc68d65bc56d2efb5d5619648935e602d66500/examples/email-assistant/application.py#L89). Would be fun to try.

**Comment by skrawcz** [comment]
@HamzaFarhan an example would be definitely welcome. I've assigned this issue to you.

What did you have mind?

**Comment by HamzaFarhan** [comment]
I have been working on utilizing LLMs for education.
So given a course outline, it uses `Instructor` to create topics and subtopics that look like this:
```python
class Subtopic(BaseModel):
    name: Annotated[str, AfterValidator(str.title)]
    concepts: Annotated[
        list[str], AfterValidator(lambda concepts: [x.title() for x in concepts])
    ] = Field(
        f"{MIN_CONCEPTS}-{MAX_CONCEPTS} concepts covered in the subtopic.",
        min_length=MIN_CONCEPTS,
        max_length=MAX_CONCEPTS,
    )


class Topic(BaseModel):
    name: Annotated[str, AfterValidator(str.title)]
    subtopics: list[Subtopic] = Field(
        f"{MIN_SUBTOPICS}-{MAX_SUBTOPICS} ordered subtopics with concepts.",
        min_length=MIN_SUBTOPICS,
        max_length=MAX_SUBTOPICS,
    )
```
With restrictions like we have on the number of `Subtopics` and `Concepts` here.
This is just the first part. We then move on to questions and quizzes with their own acceptance criteria.
As you can imagine, each step requires a human/teacher in the loop to verify/approve the things we generate.
So we can add `RAG` (I'm playing around with [LanceDB](https://lancedb.github.io/lancedb/) nowadays) on some textbook + question bank for additional content and orchestrate the whole thing using **Burr**.
I have already adapted the [email assistant](https://github.com/DAGWorks-Inc/burr/tree/main/examples/email-assistant) example to use free `Gemini Flash` with `Instructor` and it works.

**Comment by skrawcz** [comment]
Cool. I'll defer to your judgement on what example to produce.

In terms of examples, we're trying to always ensure there is:

1. a picture of the burr application.
2. a notebook with the code so that someone can run it
3. a non-notebook version to run
4. requirements.txt with dependencies
5. README with instructions on how to run things
