### ISSUE TITLE
CRAG Example

### ISSUE THREAD

**Issue by HamzaFarhan** [DAGWorks-Inc/burr#253]
**Is your feature request related to a problem? Please describe.**
Thoughts on adding **Corrective Retrieval Augmented Generation (CRAG)** as an example?

**Describe the solution you'd like**
Using `Burr`, `LanceDB`, `Instructor`, and [Exa](https://exa.ai/)(for web search). No frameworks, the SDKs directly.

**Describe alternatives you've considered**
There is a [LangGraph tutorial](https://langchain-ai.github.io/langgraph/tutorials/rag/langgraph_crag/) with `Tavily` and `Chroma` but it skips some steps and could be better overall.

**Additional context**
Here's the overview image from the [paper](https://arxiv.org/pdf/2401.15884)
<img width="1233" alt="crag" src="https://github.com/DAGWorks-Inc/burr/assets/29212086/445a9e3a-89e7-414a-87f4-191eacc4399c">

**Comment by skrawcz** [comment]
@HamzaFarhan sounds good! Happy to provide input / feedback wherever you need it.

**Comment by HamzaFarhan** [comment]
# Feedback Request

The possible routes that are guaranteed using `Instructor`:
1. names of all available LanceDB tables.
2. web_search
3. assistant
4. terminate (if the `query` is in ["exit", "quit", "q"])

So the `transitions` check for routes 2-4 and we assume that it must be _one_ of the tables otherwise.
`ask_assistant` will combine all `lancedb_results` and `exa_search_results` for context if they exist in the `state`, and then reset them to `[]`
We stop after `ask_assistant` to get the next `query` for `router`.
This is a combination of [Adaptive-RAG](https://arxiv.org/pdf/2403.14403) and [CRAG](https://arxiv.org/pdf/2401.15884).
## Adaptive-CRAG :test_tube: 

![statemachine](https://github.com/DAGWorks-Inc/burr/assets/29212086/41afa250-a6fd-45ce-8bb3-8e624479b2fb)

**Comment by skrawcz** [comment]
@HamzaFarhan at a high level this makes sense. Not sure I have feedback without actually playing with it.  Did you have some alternate designs / thoughts?

**Comment by elijahbenizzy** [comment]
This example has been merged, thank you!
