### ISSUE TITLE
Wrong order of sequence IDs in UI StepList

### ISSUE THREAD

**Issue by mmz-001** [DAGWorks-Inc/burr#254]
When steps are performed quickly the sequence IDs are listed out of order. This makes debugging quite difficult.

## Screenshots
![image](https://github.com/DAGWorks-Inc/burr/assets/70096033/c7bef08e-56b2-4a6b-bec1-0905bd3a5c29)

## Steps to replicate behavior
I was testing this out in a notebook:
```py
from burr.core import action, State, ApplicationBuilder

@action(reads=[], writes=["prompt", "chat_history"])
def human_input(state: State, prompt: str) -> State:
    chat_item = {"content": prompt, "role": "user"}
    return state.update(prompt=prompt).append(chat_history=chat_item)


@action(reads=["chat_history"], writes=["response", "chat_history"])
def ai_response(state: State) -> State:
    content = f"Your message was {state['chat_history'][-1]['content']}"
    chat_item = {"content": content, "role": "assistant"}
    return state.update(response=content).append(chat_history=chat_item)


app = (
    ApplicationBuilder()    
    .with_actions(human_input, ai_response)
    .with_transitions(
        ("human_input", "ai_response"),
        ("ai_response", "human_input"),
    )
    .with_state(chat_history=[])
    .with_entrypoint("human_input")
    .with_tracker('local')
    .build()
)

while True:
    *_, state = app.step(inputs={"prompt": input()})
    if state["prompt"] == "q":
        break
    *_, state = app.step()
    for item in state["chat_history"]:
        print(f"{item['role']}: {item['content']}")
```

## Library & System Information
burr = "0.22.3"

## Possible fix

I think the issue is coming from here when the microseconds are equal. We can sort by ```sequence_id``` in that case. Happy to send a PR.

https://github.com/DAGWorks-Inc/burr/blob/eea14bb90deb7093a4246ed7462ffe001da4a784/telemetry/ui/src/components/routes/app/AppView.tsx#L172-L188

**Comment by skrawcz** [comment]
@mmz-001 thanks for the 🐛 . If you don't mind, could you send the contents of the logs corresponding to this please? It should turn up under `~/.burr/project_name/ID`.

**Comment by mmz-001** [comment]
Sure @skrawcz. Here's the log file:
[log.json](https://github.com/user-attachments/files/15952637/log.json)

**Comment by elijahbenizzy** [comment]
@mmz-001 your assesment makes sense -- I'm rather surprised that microseconds are equal, but yeah, edge case we should have thought through. See this for evidence (from your `json` file):

```json
{"type":"begin_entry","start_time":"2024-06-24T08:38:32.692593","action":"human_input","inputs":{"prompt":"a"},"sequence_id":6}
{"type":"end_entry","end_time":"2024-06-24T08:38:32.692593","action":"human_input","result":{},"exception":null,"state":{"chat_history":[{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"},{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"},{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"},{"content":"a","role":"user"}],"__SEQUENCE_ID":6,"prompt":"a","__PRIOR_STEP":"human_input","response":"Your message was a"},"sequence_id":6}
{"type":"begin_entry","start_time":"2024-06-24T08:38:32.692593","action":"ai_response","inputs":{},"sequence_id":7}
{"type":"end_entry","end_time":"2024-06-24T08:38:32.692593","action":"ai_response","result":{},"exception":null,"state":{"chat_history":[{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"},{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"},{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"},{"content":"a","role":"user"},{"content":"Your message was a","role":"assistant"}],"__SEQUENCE_ID":7,"prompt":"a","__PRIOR_STEP":"ai_response","response":"Your message was a"},"sequence_id":7}
```

I think you're right about sequence ID -- we should add that in. The reason we don't just sort by that and call it a day is that we have more than one per step (traces, etc...), so I think we should probably sort *first* by sequence ID, then by time?

Would love a PR! Otherwise we can get to it soon.

**Comment by elijahbenizzy** [comment]
Fix is here! Will push out soon: https://github.com/DAGWorks-Inc/burr/pull/255.

**Comment by elijahbenizzy** [comment]
This has been released! Thanks for your help!
