### ISSUE TITLE
`UnicodeDecodeError` when reading from local tracker `log.jsonl`

### ISSUE THREAD

**Issue by mmz-001** [DAGWorks-Inc/burr#273]
Invalid char sequences causes errors when reloading state using local tracker. This often occurs when using web scraped data.

```shell
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 563: character maps to <undefined>
```

repro:
```py

@action(reads=[], writes=[])
def state_1(state: State) -> State:

    return state.update(test='test')


@action(reads=[], writes=[])
def state_2(state: State) -> State:
    return state.update(test='\x9d') # Invalid byte sequence in default encoding

tracker = LocalTrackingClient(
    project="test"
)

for i in range(2):
    # reloads from log.jsonl in the second run and errors
    app: Application = (
        ApplicationBuilder()
        .with_actions(state_1, state_2)
        .with_transitions(
            ('state_1', 'state_2'),
            ('state_2', 'state_1')
        ).with_tracker(tracker=tracker)
        .initialize_from(initializer=tracker, resume_at_next_action=False, default_entrypoint="state_1", default_state={})
        .with_identifiers(app_id='3')
        .build()    
    )

    app.run(
        halt_after=[
            "state_2"
        ]
    )

```
log.jsonl file:
[log.json](https://github.com/user-attachments/files/16310014/log.json)

## Fix

I believe the issue comes from here:
https://github.com/DAGWorks-Inc/burr/blob/f883885e98a0bdedc1502655ea5fb2ba81f20f49/burr/tracking/client.py#L295-L296

Maybe add `encoding='utf-8'` here?

## Library & System Information
```burr==0.24.0```
Windows

**Comment by skrawcz** [comment]
@mmz-001 thanks for the report. 

Unfortunately on Mac I cannot reproduce this issue with python 3.10.

What version of Python are you using?

**Comment by mmz-001** [comment]
`Python 3.10.11`

I think this is a Windows specific issue since the default encoding is `cp1252`

```py
import locale

print(locale.getpreferredencoding()) # cp1252
```

[SO question on this](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters)

**Comment by skrawcz** [comment]
@mmz-001 can you try `pip install burr==0.24.1rc0` and see if that fixes your issue?

**Comment by mmz-001** [comment]
Yes, it's working now. Thank you!
