### ISSUE TITLE
Improve Latency display

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#327]
**Is your feature request related to a problem? Please describe.**
The latency displayed:

1. mixes units , eg. 985ms vs 1.4 s 

Which makes it hard to scan and see what was slow.

**Describe the solution you'd like**
1. Standardize unit display.
2. Have the ability to toggle a heat map option so you can visually scan to see "slow" areas.

**Comment by elijahbenizzy** [comment]
@skrawcz thoughts now that we rewrote the traces view?

**Comment by skrawcz** [comment]
Let's close it and see what people say.
