### ISSUE TITLE
Allow one to toggle the order of sequences

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#328]
**Is your feature request related to a problem? Please describe.**
The order is reverse chronological right now when displaying an application ID trace.

Some people would like it to be chronological.

**Describe the solution you'd like**
You click the sequence ID header to toggle which way it displays. It should then remember your preference.

**Describe alternatives you've considered**
N/A

**Additional context**
This is a UI only change.

**Comment by elijahbenizzy** [comment]
Should also be part of the URL, as should the selected sequence ID
