### ISSUE TITLE
Docs - Broken link in Quickstart Page

### ISSUE THREAD

**Issue by nehiljain** [DAGWorks-Inc/burr#476]
Dead link pointing to langchain. https://burr.dagworks.io/getting_started/simple-example/langchain.io

# Current behavior
1. Link to langchain.io is incorrect

## Additional context
This bug was found using an automation built by https://www.demodrive.tech/. We are looking at popular OSS projects and helping them ensure their documentation is error-proof.

**Comment by skrawcz** [comment]
Fixed in #478  - thanks!
