### ISSUE TITLE
Bug in Docs - Code template links are not working on Agent Patterns page

### ISSUE THREAD

**Issue by nehiljain** [DAGWorks-Inc/burr#477]
Links for code templates on the [Agent patterns page](https://burr.dagworks.io/examples/agents/agent-patterns/) need to be corrected.

- https://github.com/DAGWorks-Inc/burr/tree/main/examples/templates/multi_modal_agent
- https://github.com/DAGWorks-Inc/burr/tree/main/examples/templates/multi_agent_collaboration
- https://github.com/DAGWorks-Inc/burr/tree/main/examples/templates/agent_supervisor
- https://github.com/DAGWorks-Inc/burr/tree/main/examples/templates/hierarchical_agent_teams

# Current behavior
Link to code templates are 404s.

## Additional context
This bug was found using an automation built by https://www.demodrive.tech/. We are looking at popular OSS projects and helping them ensure their documentation is error-proof.

**Comment by skrawcz** [comment]
Fixed in #478 thanks!
