### ISSUE TITLE
Spec'ing state saving and loading

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#71]
Use cases:

1. User controls how the app is started via `with_state()` and `with_entrypoint()`.
2. User delegates to a persister & burr to reload state for a given partition key, app_id -- via `with_db()` and `with_identifier`. Seqeuence id is either 0 or loaded from state, or passed in via `with_identifier`. 
3. user can add a persister via `with_persistence` -- need to deduplicate hooks potentially

Notes:
 - tracker & persister can be same object
 - can have separate persister and tracker

Requirements:
 - app knows about partition key
 - app knows about app_id or generates one
 - app sets sequence id to 0 unless it loads one from prior state
 - hooks get passed partition key, app_id, sequence no, position

**Comment by elijahbenizzy** [comment]
Implemented by #73
